name: image push workflow
on: push
jobs:
    image_build_push_job:
      runs-on: ubuntu-latest
        permissions:
          packages: write
      steps:
        - name: login-ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - id: build-push
          run: |
            echo "Test message"
            cat > ./Dockerfile <<EOF
            FROM alpine
            CMD ["echo", "Hello container!"]
            EOF
            docker build -t ghcr.io/lkatalin/test-tag:latest .
            docker push ghcr.io/lkatalin/test-tag:latest
            echo "Success"
