name: image push workflow
on: push
jobs:
    image_push_job:
      runs-on: ubuntu-latest
      steps:
        - id: step1
          run: |
            echo "Test message"
            cat > ./Dockerfile <<EOF
            FROM alpine
            CMD ["echo", "Hello container!"]
            EOF
            echo "Success"
