name: image push workflow
on: push
jobs:
    image_build_push_job:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write
      steps:
        - name: login-ghcr
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: build-push
          run: |
            echo "Test message build-push"
            cat > ./Dockerfile <<EOF
            FROM alpine
            CMD ["echo", "Hello container!"]
            EOF
            docker build -t ghcr.io/lkatalin/test-tag:latest .
            docker push ghcr.io/lkatalin/test-tag:latest
            echo "Success build-push"
        - name: install-cosign
          uses: sigstore/cosign-installer@main
          with:
            cosign-release: 'v2.2.4'
        - name: check-cosign-install
          run: cosign version
        - name: build-sign-push
          run: |
            echo "Test message build-sign-push"
            cat > ./Dockerfile <<EOF
            FROM alpine
            CMD ["echo", "Hello container!"]
            EOF
            docker build -t ghcr.io/lkatalin/test-signed:latest .
            docker push ghcr.io/lkatalin/test-signed:latest
            cosign sign -y ghcr.io/lkatalin/test-signed:latest
            echo "Success build-sign-push"
